### PR TITLE
Add requirements needed to run the project

### PR DESCRIPTION
**Pull request by durvalcarvalho**

### CODE REVIEW

**Comment by durvalcarvalho** [comment]
I just realized that all these packages are dependent on the main packages (PyYAML, py2neo, Flask). It's cleaner to just list these ones.

**Comment by weihesdlegend** [comment]
So what’s your opinion? The original requirement.txt is good enough? If so please modify the commit accordingly

**Comment by durvalcarvalho** [comment]
I think it's better now. I had already modified.

**Comment by weihesdlegend** [comment]
Can you please specify how to install virtualenv ?

**Comment by durvalcarvalho** [comment]
Done!

**Comment by sananand007** [comment]
We can Just have, do we need virtualenv 
`
# macOS/Linux
sudo apt-get install python3-venv    # If needed
python3 -m venv env

# Windows
python -m venv env
`

**Comment by sananand007** [comment]
whatever you said is good suggestions mate, we will put the requirements.txt in a cleaner way. tnx.

**Pull request closed without merging**
